travis:
  secure:
    BINSTAR_TOKEN: uCIuLDSuAhBN8DSXmKtfxASaIuGWaSmzUG49PtzvaJ3c3bw/nknC+u7//s3F0a7uq7+Z7cZ0V/DNitbG3HFGSTwVE5ElPJVWm8TxAkmZfB+baXxQNW7Hin8fZWHF/71fRcGsYxHvfNfTkMO2ExJet6WUBd2puhCFzZx+3KSSK6iIVzxdTKWLa7mf9ir5+ewXqVExSuFKhsRjVkXignVSbp9NdOmVJ21eTFxjghD+ehNdKPa7JYUBM1GGga4+nQ0qZLLrHPhB02oIxj60bwCM369ByoeZSek9Rhumhk2UulxUTTRwXB7L4xFz+CWJ5fKFAjOQ2v6zvzv1RHgzq0b+C5A/DGHoeW8Ea1BgqU0SikWo/jxc9R20QITciZZn/18x/6+RWIGMmjwTGK3B/Us87dQC2OYFaawwA8zraJl+qTunFWFb7XHKWpHSEXDCEb+GFFVTVaAjHUK27VGCg2Tm7CcIneKQ7QGH3liKHGaVYqGUFZVxk3sskOJxidrf+9TTjdKinkC7hrUJP3wnjq9HdyPaqjYGW/lbimr3zv09w1oQ79+GGS9J2C8XvAUt/myjX0XJSWx7s+b45gBE0n0++vcF7osEE5AP+adqgFI04dIKMNeJwxLyjzCpd5YBf0PV3ApwKgrZjjfmazR5xSnPtDH0va8NRv1FPaixBcJK3zU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
